blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/faneX-ID/integrations/discussions
    about: Ask questions and discuss integrations
  - name: ðŸ“š Documentation
    url: https://fanex-id.github.io/
    about: Check our documentation
